VIRTUAL_WIDTH = 640
VIRTUAL_HEIGHT = 360

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = VIRTUAL_HEIGHT/12

MAX_ACTIONBAR_SIZE = 4

-- --
-- -- map constants
-- --
MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (9 * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = ((VIRTUAL_HEIGHT * 0.9) - (9 * TILE_SIZE)) / 2

-- --
-- -- ui rendering offsets
-- --
ACTIONBAR_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAX_ACTIONBAR_SIZE * TILE_SIZE)) / 2
ACTIONBAR_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT * 0.9) + (VIRTUAL_HEIGHT * 0.1 - TILE_SIZE)/2

--DIRECTIONS
DIR_UP = 1
DIR_RIGHT = 2
DIR_DOWN = 3
DIR_LEFT = 4
VEC_UP = Vector(0, -1)
VEC_RIGHT = Vector(1, 0)
VEC_DOWN = Vector(0, 1)
VEC_LEFT = Vector(-1, 0)

DIR_VECTORS = {}
DIR_VECTORS[DIR_UP] = VEC_UP
DIR_VECTORS[DIR_RIGHT] = VEC_RIGHT
DIR_VECTORS[DIR_DOWN] = VEC_DOWN
DIR_VECTORS[DIR_LEFT] = VEC_LEFT 

--TARGETING TYPES
UNIT_TARGET = 1
AREA_TARGET = 2
TILE_TARGET = 3	
AOE = 4
SELF = 5
NONE = 6

ALLY_TEAM = 1
ENEMY_TEAM = 2
NEUTRAL = 3

-- -- tile IDs