VIRTUAL_WIDTH = 640
VIRTUAL_HEIGHT = 360

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = VIRTUAL_HEIGHT/12

MAX_ACTIONBAR_SIZE = 6

-- --
-- -- entity constants
-- --
-- healer_WALK_SPEED = 60

-- --
-- -- map constants
-- --
MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (9 * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = ((VIRTUAL_HEIGHT * 0.9) - (9 * TILE_SIZE)) / 2

-- --
-- -- ui rendering offsets
-- --
ACTIONBAR_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAX_ACTIONBAR_SIZE * TILE_SIZE)) / 2
ACTIONBAR_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT * 0.9) + (VIRTUAL_HEIGHT * 0.1 - TILE_SIZE)/2

--DIRECTIONS
DIR_UP = 1
DIR_RIGHT = 2
DIR_DOWN = 3
DIR_LEFT = 4
VEC_UP = Vector(0, -1)
VEC_RIGHT = Vector(1, 0)
VEC_DOWN = Vector(0, 1)
VEC_LEFT = Vector(-1, 0)

DIR_VECTORS = {}
DIR_VECTORS[DIR_UP] = VEC_UP
DIR_VECTORS[DIR_RIGHT] = VEC_RIGHT
DIR_VECTORS[DIR_DOWN] = VEC_DOWN
DIR_VECTORS[DIR_LEFT] = VEC_LEFT 

--TARGETING TYPES
UNIT_TARGET = 1
AREA_TARGET = 2
AOE = 3
SELF = 4
NONE = 5

-- -- tile IDs
-- --
-- TILE_TOP_LEFT_CORNER = 4
-- TILE_TOP_RIGHT_CORNER = 5
-- TILE_BOTTOM_LEFT_CORNER = 23
-- TILE_BOTTOM_RIGHT_CORNER = 24

-- TILE_EMPTY = 19

-- TILE_FLOORS = {
--     7, 8, 9, 10, 11, 12, 13,
--     26, 27, 28, 29, 30, 31, 32,
--     45, 46, 47, 48, 49, 50, 51,
--     64, 65, 66, 67, 68, 69, 70,
--     88, 89, 107, 108
-- }

-- TILE_TOP_WALLS = {58, 59, 60}
-- TILE_BOTTOM_WALLS = {79, 80, 81}
-- TILE_LEFT_WALLS = {77, 96, 115}
-- TILE_RIGHT_WALLS = {78, 97, 116}